# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FreeRTOS Hardware Abstraction Layer
email: kernel@andy89.org
description: > # this means to ignore newlines until "baseurl:"
  FreeRTOS Hardware Abstraction Layer, a simple and fast HAL for multiply 
  Architecture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://freertoshal.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  FreeRTOSHAL

# Build settings
markdown: kramdown
