var annotated_dup =
[
    [ "accel_generic", "structaccel__generic.html", "structaccel__generic" ],
    [ "adc_generic", "structadc__generic.html", "structadc__generic" ],
    [ "capture_generic", "structcapture__generic.html", "structcapture__generic" ],
    [ "clock_generic", "structclock__generic.html", "structclock__generic" ],
    [ "example_generic", "structexample__generic.html", "structexample__generic" ],
    [ "example_ops", "structexample__ops.html", "structexample__ops" ],
    [ "gpio_generic", "structgpio__generic.html", "structgpio__generic" ],
    [ "gpio_pin_generic", "structgpio__pin__generic.html", "structgpio__pin__generic" ],
    [ "gyro_generic", "structgyro__generic.html", "structgyro__generic" ],
    [ "hal", "structhal.html", "structhal" ],
    [ "mpu9250", "structmpu9250.html", "structmpu9250" ],
    [ "mpu9250_accel", "structmpu9250__accel.html", "structmpu9250__accel" ],
    [ "mpu9250_gyro", "structmpu9250__gyro.html", "structmpu9250__gyro" ],
    [ "mpu9250_vector", "structmpu9250__vector.html", "structmpu9250__vector" ],
    [ "pwm_generic", "structpwm__generic.html", "structpwm__generic" ],
    [ "sd_generic", "structsd__generic.html", "structsd__generic" ],
    [ "sd_response", "structsd__response.html", "structsd__response" ],
    [ "sd_setting", "structsd__setting.html", "structsd__setting" ],
    [ "spi_generic", "structspi__generic.html", "structspi__generic" ],
    [ "spi_opt", "structspi__opt.html", "structspi__opt" ],
    [ "spi_slave_generic", "structspi__slave__generic.html", "structspi__slave__generic" ],
    [ "timer_generic", "structtimer__generic.html", "structtimer__generic" ],
    [ "uart_generic", "structuart__generic.html", "structuart__generic" ],
    [ "vector", "structvector.html", "structvector" ]
];